main:
  - name: Page
    identifier: Page
    weight: 100
    url: https://spacerpod.netlify.app
    params:
      header: Personal
      icon:
        vendor: font-awesome-solid
        name: Page

  - name: wiki
    parent: Page
    url: https://spacerpod.netlify.app/en/docs
    weight: 1
    params:
      icon:
        vendor: bs
        name: book
        className: text-primary
      description: The Wiki

  - identifier: support-divider
    parent: Page
    weight: 10
    params:
      divider: true

  - name: GitHub
    parent: Page
    url: https://github.com/stardoom4
    weight: 11
    params:
      icon:
        vendor: fab
        name: github
      description: The code repository.
